### ISSUE TITLE
使用launchOnlyresult闪退

### ISSUE THREAD

**Issue by hzl1378252** [AleynP/MVVMLin#13]
launchGo({
            val result = homeRepository.login(map)
            if (!result.isSuccess()) {
                ToastUtils.showShort("" + result.message)
            }
        })

        launchOnlyresult({ homeRepository.login(map) }, {

        }, {
            // 这里是Error 返回   ()
        })
launchOnlyresult闪退 但是launchGo就是正常的

**Comment by hzl1378252** [comment]
我把结果返回true就可以了，就是走false的时候会闪退 不太明白哪里的问题
2020-07-23 17:37:10.089 28862-28862W/TypefaceUtils: get metaData of com.example.logo failed
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
        at miui.util.TypefaceUtils.isUsingMiuiFont(TypefaceUtils.java:300)
        at miui.util.TypefaceUtils.usingMiuiFonts(TypefaceUtils.java:289)
        at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:570)
        at android.widget.TextView.replaceTypeface(TextView.java:4380)
        at android.widget.TextView.setTypeface(TextView.java:4369)
        at android.widget.TextView.setTypeface(TextView.java:2268)
        at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2157)
        at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2128)
        at android.widget.TextView.applyTextAppearance(TextView.java:4083)
        at android.widget.TextView.<init>(TextView.java:1604)
        at android.widget.TextView.<init>(TextView.java:968)
        at android.widget.TextView.<init>(TextView.java:964)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createView(LayoutInflater.java:780)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at android.widget.Toast.makeText(Toast.java:290)
        at android.widget.Toast.makeText(Toast.java:276)
        at com.blankj.utilcode.util.ToastUtils$ToastFactory.makeNormalToast(ToastUtils.java:366)
        at com.blankj.utilcode.util.ToastUtils$ToastFactory.makeToast(ToastUtils.java:352)
        at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:263)
        at com.blankj.utilcode.util.Utils.runOnUiThread(Utils.java:170)
        at com.blankj.utilcode.util.ToastUtils.show(ToastUtils.java:258)
        at com.blankj.utilcode.util.ToastUtils.show(ToastUtils.java:254)
        at com.blankj.utilcode.util.ToastUtils.showShort(ToastUtils.java:141)
        at com.aleyn.mvvm.base.BaseActivity$registorDefUIChange$3.onChanged(BaseActivity.kt:69)
        at com.aleyn.mvvm.base.BaseActivity$registorDefUIChange$3.onChanged(BaseActivity.kt:21)
        at com.aleyn.mvvm.event.SingleLiveEvent$observe$1.onChanged(SingleLiveEvent.kt:56)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.aleyn.mvvm.event.SingleLiveEvent.setValue(SingleLiveEvent.kt:64)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by hzl1378252** [comment]
知道了 kotlin的语法错误

**Comment by hzl1378252** [comment]
走true是好的 走false就会闪退
data class BaseResult<T>(
    val code: Int,
    val message: String,
    val data: T
) : IBaseResponse<T> {

    override fun code() = code

    override fun msg() = message

    override fun data() = data

    override fun isSuccess() = false
}

**Comment by hzl1378252** [comment]
错误信息
2020-07-23 17:55:22.983 3527-3527/  W/TypefaceUtils: get metaData of com.example.logo failed
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
        at miui.util.TypefaceUtils.isUsingMiuiFont(TypefaceUtils.java:300)
        at miui.util.TypefaceUtils.usingMiuiFonts(TypefaceUtils.java:289)
        at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:570)
        at android.widget.TextView.replaceTypeface(TextView.java:4380)
        at android.widget.TextView.setTypeface(TextView.java:4369)
        at android.widget.TextView.setTypeface(TextView.java:2268)
        at androidx.appcompat.widget.AppCompatTextView.setTypeface(AppCompatTextView.java:711)
        at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2157)
        at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2144)
        at android.widget.TextView.applyTextAppearance(TextView.java:4083)
        at android.widget.TextView.<init>(TextView.java:1604)
        at android.widget.TextView.<init>(TextView.java:968)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:100)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:194)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1550)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1601)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.afollestad.materialdialogs.utils.ViewsKt.inflate(Views.kt:39)
        at com.afollestad.materialdialogs.utils.ViewsKt.inflate$default(Views.kt:38)
        at com.afollestad.materialdialogs.internal.message.DialogContentLayout.addCustomView(DialogContentLayout.kt:143)
        at com.afollestad.materialdialogs.customview.DialogCustomViewExtKt.customView(DialogCustomViewExt.kt:65)
        at com.afollestad.materialdialogs.customview.DialogCustomViewExtKt.customView$default(DialogCustomViewExt.kt:55)
        at com.aleyn.mvvm.base.BaseActivity.showLoading(BaseActivity.kt:86)
        at com.aleyn.mvvm.base.BaseActivity.access$showLoading(BaseActivity.kt:21)
        at com.aleyn.mvvm.base.BaseActivity$registorDefUIChange$1.onChanged(BaseActivity.kt:63)
        at com.aleyn.mvvm.base.BaseActivity$registorDefUIChange$1.onChanged(BaseActivity.kt:21)
        at com.aleyn.mvvm.event.SingleLiveEvent$observe$1.onChanged(SingleLiveEvent.kt:56)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.aleyn.mvvm.event.SingleLiveEvent.setValue(SingleLiveEvent.kt:64)
        at com.aleyn.mvvm.event.SingleLiveEvent.call(SingleLiveEvent.kt:72)
        at com.aleyn.mvvm.base.BaseViewModel.launchOnlyresult(BaseViewModel.kt:83)
        at com.aleyn.mvvm.base.BaseViewModel.launchOnlyresult$default(BaseViewModel.kt:81)
        at com.example.logo.app.ui.login.LoginVM.login(LoginVM.kt:48)
        at com.example.logo.app.ui.login.LoginActivity$initClick$1.invoke(LoginActivity.kt:56)
        at com.example.logo.app.ui.login.LoginActivity$initClick$1.invoke(LoginActivity.kt:23)
        at com.qmuiteam.qmui.kotlin.ViewKtKt$throttleClick$1.onClick(ViewKt.kt:15)
        at android.view.View.performClick(View.java:7163)
        at android.view.View.performClickInternal(View.java:7140)
        at android.view.View.access$3500(View.java:813)
        at android.view.View$PerformClick.run(View.java:27428)
2020-07-23 17:55:22.984 3527-3527/com.example.logo W/TypefaceUtils:     at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
