### ISSUE TITLE
双击导航栏，请求数据，偶尔出现

### ISSUE THREAD

**Issue by RookieExaminer** [AleynP/MVVMLin#18]
2020-09-09 16:35:30.495 9965-9965/com.pcl.mvvm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pcl.mvvm, PID: 9965
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.aleyn.mvvm.binding.TabLayoutAdapter.setTabText(TabLayoutAdapter.kt:29)
        at com.pcl.mvvm.databinding.ProjectFragmentBindingImpl.executeBindings(ProjectFragmentBindingImpl.java:162)
        at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:473)
        at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:445)
        at androidx.databinding.ViewDataBinding$7.run(ViewDataBinding.java:197)
        at androidx.databinding.ViewDataBinding$8.doFrame(ViewDataBinding.java:291)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by q805699513** [comment]
双击导航栏是指导航栏的哪个键，返回还是home

**Comment by RookieExaminer** [comment]
> 双击导航栏是指导航栏的哪个键，返回还是home

底部的几个按钮
