### ISSUE TITLE
BaseActivity中的写法限制了BaseActivity只能有儿子，不能有孙子~

### ISSUE THREAD

**Issue by xiaobo0113** [AleynP/MVVMLin#21]
```
class DetailActivity : MyBaseActivity()
abstract class MyBaseActivity : BaseActivity<NoViewModel, ViewDataBinding>() {
}
```

BaseActivity.kt：
```
private fun initViewDataBinding() {
	val cls =
		(javaClass.genericSuperclass as ParameterizedType).actualTypeArguments[1] as Class<*>
	if (ViewDataBinding::class.java != cls && ViewDataBinding::class.java.isAssignableFrom(cls)) {
		mBinding = DataBindingUtil.setContentView(this, layoutId())
		mBinding?.lifecycleOwner = this
	} else setContentView(layoutId())
	createViewModel()
}
```

异常：
```
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
        at com.aleyn.mvvm.base.BaseActivity.initViewDataBinding(BaseActivity.kt:49)
        at com.aleyn.mvvm.base.BaseActivity.onCreate(BaseActivity.kt:31)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
```

**Comment by xiaobo0113** [comment]
需要这样写：
`MyBaseActivity<VM : BaseViewModel, DB : ViewDataBinding> : BaseActivity<VM, DB>`
